Ability to list and remove running applications

diff --git a/util/kh/khctl b/util/kh/khctl
--- a/util/kh/khctl
+++ b/util/kh/khctl
@@ -1,5 +1,4 @@
 #!/bin/bash
-#set -x
 
 #####################################
 #
@@ -22,7 +21,6 @@ declare -r KHCONSDIR=${KHCTL_CONSDIR:-$KHBASEDIR/Consoles}
 declare -r KHCTLDIR=${KHCTL_CTLDIR:-$KHBASEDIR/Ctl}
 declare -r KHTUPLEDIR=${KH_TUPLEDIR:-$KHBASEDIR/KHTuples}
 declare -r KHTUPLECTRLDIR=${KH_TUPLECTRLDIR:-$KHCTLDIR}
-
 declare -r KHCONIDFILE=${KHCTL_CONIDFILE:-$KHCTLDIR/ConID}
 declare -r KHCONIDSTART=${KHCTL_CONIDSTART:-2}
 declare -r KHCONIDEND=${KHCTL_CONIDEND:-$(printf "%d" 0xffffffff)}
@@ -43,13 +41,11 @@ declare -r KHCTRLID=${KHCTL_CTRLID:-0}
 declare -r KHTTYMAJOR=${KHCTL_TTYMAJOR:-230}
 declare -r KHXIPFILE=${KHCTL_XIPFILE:-/proc/device-tree/u-boot-env/xip}
 declare -r KHNATIPFILE=${KHCTL_NATFILE:-/proc/device-tree/u-boot-env/natip}
-
 declare -r FREEOWNER='_FREE_'
 declare -r FREEPNET=$KHFREENETID
 declare -r FREEINETFLG=0
 declare -r FREEXNETFLG=0
 declare -r FREECONID=$KHCTRLID
-
 declare BUFFERVAR
 declare -i BUFFERTTY=1
 
@@ -393,7 +389,7 @@ isquish()
 
 SESAcreateNet()
 {
-  set -x
+#  set -x
   local nid=$1
   local tapcmd=""
   local dir=$SESANETDIR/$nid
@@ -411,12 +407,12 @@ SESAcreateNet()
   fi
 
   # optional tap interface
-  if [[ $( ifconfig | grep -o $tap) ]]; then
-    tapcmd="-t $tap" 
-  else
-      if [[ -n $tap ]]; then
-         echo "Error: unable to locate $tap"
-      fi
+  if [[ -n $tap ]]; then
+    if [[ $( ifconfig | grep -o $tap) ]]; then
+      tapcmd="-t $tap" 
+    else
+      echo "Error: unable to locate $tap"
+    fi
   fi
 
   vde_switch $tapcmd -d -s $dir/sock -M $dir/mgmt -p $dir/pid 
@@ -446,21 +442,71 @@ function SESAcleanAll
   rm -rf $SESANETDIR/* 
 }
 
-
-function SESAdeleteNode
+function SESAcleanApp
 {
-  local dir=$KHCONDIR/$cid
+  app=$1
+  if [[ -z $app ]]; then
+      echo "Error: No app name"
+      exit 1
+  fi
+
+  local nodes=()
+  local consoles=( $(tupleCmd echo Node "*:$app:*:*:*") )
+  if [[ $consoles == "*:$app:*:*:*" ]];then
+    echo "Error: App not found. Use khls to list active apps"
+    exit 1
+  fi
+  local network=( $(tupleCmd echo Pnet "*:$app") )
+  local files=( ${consoles[@]/*:/$KHCONSDIR/} )
+  local net=$( echo $network | cut -d ':' -f 1 )
+
+  if [[ ! (${#consoles[@]} > 0) ]]; then
+    echo "ERROR: $app not found"
+    exit 1
+  fi
+    
+  for i in ${consoles[@]}
+  do
+    nodes+=($( echo $i | cut -d ':' -f 1 ))
+  done
+  
+  # delete processes 
+  kill $( cat ${files[@]/%//nodes/\*/pid} | sort -u )
+  kill $( cat $SESANETDIR/$net/pid )
+
+  # remove tuples
+  lock tuples
+    locked_rm_users "$1" "*"
+    locked_rm_pnets "$net" "$1"
+    locked_rm_nodes "*" "$1" "*" "*" "*" "*"
+    for j in ${nodes[@]}
+    do
+      echo $j
+      locked_touch_nodes "$j" "$FREEOWNER" "$FREEPNET"\
+        "$FREEINETFLG" "$FREEXNETFLG" "$FREECONID"
+    done
+  unlock tuples
+  
+  # clean up files
+  rm -rf $SESANETDIR/$net
+  rm -rf $( echo ${files[@]} | sort -u )
+
 }
 
-function SESAdeleteNet
+function SESAlistApp
 {
-  local nid=$1
-  local dir=$SESANETDIR/$nid
+  local consoles=( $(tupleCmd echo Node "!(*:_FREE_:*:*:*)") )
+  local files=()
 
-  if [[ -a $dir/pid ]]; then
-    kill $(cat $dir/pid)
-  fi
-  return $?
+  for i in ${consoles[@]}
+  do
+    files+=($( echo $i | cut -d ':' -f 2 ))
+  done
+
+  for i in $( echo ${files[@]} | tr ' ' '\n' | sort -u | tr '\n' ' ' )
+  do
+    echo $i $( grep -o $i <<< ${files[*]} | wc -l )
+  done
 }
 
 function SESAgenerateMac()
@@ -1165,7 +1211,7 @@ locked_unchecked_tupleCmd()
   then 
     rc=0
   else
-#    eval echo "ERROR: $FUNCNAME: $cmd $typedir/$tuplepattern: FAILED"  >&2
+    #eval echo "ERROR: $FUNCNAME: $cmd $typedir/$tuplepattern: FAILED"  >&2
     rc=255
   fi
 
@@ -1184,7 +1230,6 @@ function tupleCmd
     echo "USAGE: $FUNCNAME <cmd> <type> <tuplepattern>" >&2
     return 255
   fi
-
 
   type -a $cmd >/dev/null 2>&1
 
diff --git a/util/kh/setup b/util/kh/setup
--- a/util/kh/setup
+++ b/util/kh/setup
@@ -74,7 +74,6 @@ chmod 755 $base/makeapp
 
 cat > $base/makeapp << EOF
 #!/bin/bash
-set -x
 base=$base
 ulnx=$ulnx
 bare=$bare
@@ -84,13 +83,11 @@ EOF
 echo 'app=$1
 if [[ -z $app ]]
 then
-  echo "ERROR: include application name"
+  echo "USAGE: $0 <appName>"
   exit -1
 fi
 
-echo " building linux app"
 make -C $ulnx src/app/$app/$app
-echo " building baremetal app"
 make -C $bare src/app/$app/$app.$imgtype
   
 '>> $base/makeapp 
@@ -114,60 +111,94 @@ export SESA_GET=khget
 EOF
 
 echo '
+src=/home/jmcadden/work/sesa/EbbRT
+base=.
+ulnx=./ulnx
+bare=./bare
+imgtype=iso
+export SESA_GET=/home/jmcadden/work/sesa/EbbRT/util/kh/khget
+export SESA_UTIL=/home/jmcadden/work/sesa/EbbRT/util/kh/khctl
+export SESA_BASEDIR=/scratch/build/khdb
+
+declare app
+declare count
+declare name
+declare tap
+declare fcnt
+declare -i lp=0
+declare -i optcount=0
+
+while getopts "n:t:f:" OPT
+do 
+  case $OPT in
+      ("n") name="$OPTARG"; (( optcount=optcount + 2));;
+      ("t") tap="$OPTARG"; (( optcount=optcount + 2));;
+      ("f") fcnt="$OPTARG"; (( optcount=optcount + 2));;
+      ("P") lp=1; (( optcount=optcount + 1));;
+  esac
+done
+
+shift $optcount
 app=$1
-option=$2
-if [[ -n $3 ]]; then count=$3; else count=1; fi
-if [[ -n $4 ]]; then 
+count=$2
+if [[ -z $count ]]; then count=1; fi
+
+
+if [[ -z $app  || -z $count ]]
+then
+  echo "USAGE: $0 [-n name] [-t tap] [-f fcnt] <app> <count>"
+  echo "     -n  name : specify name of the job " 
+  echo "     -t  tap  : tap interface (sudo required)" 
+  echo "     -f  fcnt : load "fcnt"-many linux front-end processes" 
+  #echo "     -P       : run front-end as a local process" 
+  echo "     app      : EbbRT application to run (e.g., HelloWorld)"
+  echo "     count    : num of baremetal nodes to boot"
+  exit 1;
+fi
+
+if [[ -n $tap ]]; then 
     if [[ $UID != 0 ]]; then
       echo "Error: sudo required for TAP interfaces"
       exit 1
     else
-      export SESA_TAP=$4
+      export SESA_TAP=$tap
     fi
 fi
 
-if [[ -z $app  || ! ($option > 0) ]]
-then
-  echo "USAGE: $0 <appName> <runType> [bareCount] [tap] " 
-  echo "     appName  : application/boot img to run"
-  echo "     runType  : execution arrangement"
-  echo "                  1)  baremetal-only (qemu)"
-  echo "                  2)  front-end process, many baremetal (qemu)"
-echo "                  3)  linux front-end. Treats appName as boot image (qemu)" 
-  echo "   bareCount  : number of backend nodes, default is 1" 
-  echo "         tap  : tap interface (sudo required)" 
-  exit 1;
-fi
-
-APPNAME="$app$RANDOM"
+if [[ -z $name ]]; then name=$app$RANDOM; fi
+APPNAME="$name"
 BARE_IMG=$(readlink -f ${base}/bare/src/app/$app/$app.$imgtype)
 FNT_IMG=$(readlink -f ${base}/ulnx/src/app/$app/$app)
 
-case $option in
-    1)
-    bkcmd="$($SESA_GET $APPNAME $BARE_IMG $count)"
-    echo $bkcmd
-    ;;
-    ########################
-    2)
-    xterm -hold -e $FNT_IMG &
-    sleep 5
-    bkcmd="$($SESA_GET $APPNAME $BARE_IMG $count)"
-    ;;
-    ########################
-    3)
-    if [[ ! (-a $app) ]]; then
-      echo "Error: boot image not found $app"
-      exit 1
+if [[ ! -a $BARE_IMG ]]; then
+  echo "ERROR: binaries not found for $app. Try running ./makeapp $app"
+  exit 1
+fi
+
+echo "Loading nodes for $name"
+
+# frontend 
+if [[ -n $fcnt && $fcnt > 0 ]]; then
+    if [[ $lp > 0 ]]; then
+      # local process
+      for i in {1..$fcnt}; do
+        xterm -hold -e $FNT_IMG &
+      done
+    else
+      # linux vm front-ends
+      echo "#!/bin/bash" > $ulnx/run
+      echo "/root/ebbrt/src/app/$app/$app" >> $ulnx/run
+      mnt=$(readlink -f ${base}/ulnx)
+      ftcmd="$($SESA_GET -f -m $mnt $APPNAME $sesalnx $fcnt)"
+      serials=$(echo "$ftcmd" | grep serial | while read node nn junk path; do echo $path; done)
+
+      for sock in $serials; do
+        xterm -e socat - UNIX-CONNECT:$sock &
+      done
     fi
-    ftcmd="$($SESA_GET -m $base -i "linux"$RANDOM $app )" 
-    serials=$(echo "$ftcmd" | grep serial | while read node nn junk path; do echo $path; done)
-    for sock in $serials; do
-      xterm -e socat - UNIX-CONNECT:$sock &
-    done
-    exit
-    ;;
-    ########################
-    *) echo "Error: invalid execution choice";;
-esac
+  sleep 3
+fi
+
+bkcmd="$($SESA_GET $APPNAME $BARE_IMG $count)"
+echo $bkcmd
 ' >> $base/runapp 
